# global default
#container:
#  image: gradle:jdk8

build_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  gradle_cache:
    folder: ~/.gradle/caches
#   install_zip_script:
#      pkg install -y zip
#      cd /usr/ports/archivers/zip
#      make install clean
#   install_sdkman_script:
#    - curl -s "https://get.sdkman.io" | bash
#    - source "/home/user/.sdkman/bin/sdkman-init.sh"
  install_gradle_script:
    #- sdk install gradle
    - pkg install -y gradle
  install_libreoffice_script:
    - pkg install -y libreoffice
  build_script:
    - gradle build -i
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete