server:
  port: 8080
  tomcat:
    max-http-post-size: 125829120
  
spring:
  http:
    multipart:
      max-file-size: 110MB
      max-request-size: 120MB
  servlet:
    multipart:
      max-file-size: 110MB
      max-request-size: 120MB
  application:
    name: JODConverter Sample Rest Api

jodconverter:
  local:
    enabled: true
    port-numbers: 2002,2003
  
logging:
  level:
    org.jodconverter: debug
